id <- c(1,2,3)
name <- c("srihari","navya","manoj")
age <- c(21,22,19)
df = data.frame(id,name,age)
print(df)
print(df[1:2, ])
print(df[,1:2])
print(subset(df, name=="srihari"|age>20))
df[[3]][3] =18
print(df)
newdf = cbind(df, rank=c(3,2,1))
print(newdf)
newdf1 = rbind(newdf, data.frame(id=4, name='uday', age=22, rank=30))
print(newdf1)